// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
// NOTE: after re-running compileAttributes(), re-add: #include "maxdiff.h"

#include "maxdiff.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// llmnl_con
double llmnl_con(vec const& betastar, vec const& y, mat const& X, vec const& SignRes, IntegerVector p_vec);
RcppExport SEXP _maxdiff_llmnl_con(SEXP betastarSEXP, SEXP ySEXP, SEXP XSEXP, SEXP SignResSEXP, SEXP p_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec const& >::type betastar(betastarSEXP);
    Rcpp::traits::input_parameter< vec const& >::type y(ySEXP);
    Rcpp::traits::input_parameter< mat const& >::type X(XSEXP);
    Rcpp::traits::input_parameter< vec const& >::type SignRes(SignResSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p_vec(p_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(llmnl_con(betastar, y, X, SignRes, p_vec));
    return rcpp_result_gen;
END_RCPP
}
// rhierMnlRwMixture_rcpp_loop
List rhierMnlRwMixture_rcpp_loop(List const& lgtdata, mat const& Z, vec const& deltabar, mat const& Ad, mat const& mubar, mat const& Amu, double nu, mat const& V, double s, int R, int keep, int nprint, bool drawdelta, mat olddelta, vec const& a, vec oldprob, mat oldbetas, vec ind, vec const& SignRes, List const& p_it_list);
RcppExport SEXP _maxdiff_rhierMnlRwMixture_rcpp_loop(SEXP lgtdataSEXP, SEXP ZSEXP, SEXP deltabarSEXP, SEXP AdSEXP, SEXP mubarSEXP, SEXP AmuSEXP, SEXP nuSEXP, SEXP VSEXP, SEXP sSEXP, SEXP RSEXP, SEXP keepSEXP, SEXP nprintSEXP, SEXP drawdeltaSEXP, SEXP olddeltaSEXP, SEXP aSEXP, SEXP oldprobSEXP, SEXP oldbetasSEXP, SEXP indSEXP, SEXP SignResSEXP, SEXP p_it_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List const& >::type lgtdata(lgtdataSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< vec const& >::type deltabar(deltabarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Ad(AdSEXP);
    Rcpp::traits::input_parameter< mat const& >::type mubar(mubarSEXP);
    Rcpp::traits::input_parameter< mat const& >::type Amu(AmuSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< mat const& >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type keep(keepSEXP);
    Rcpp::traits::input_parameter< int >::type nprint(nprintSEXP);
    Rcpp::traits::input_parameter< bool >::type drawdelta(drawdeltaSEXP);
    Rcpp::traits::input_parameter< mat >::type olddelta(olddeltaSEXP);
    Rcpp::traits::input_parameter< vec const& >::type a(aSEXP);
    Rcpp::traits::input_parameter< vec >::type oldprob(oldprobSEXP);
    Rcpp::traits::input_parameter< mat >::type oldbetas(oldbetasSEXP);
    Rcpp::traits::input_parameter< vec >::type ind(indSEXP);
    Rcpp::traits::input_parameter< vec const& >::type SignRes(SignResSEXP);
    Rcpp::traits::input_parameter< List const& >::type p_it_list(p_it_listSEXP);
    rcpp_result_gen = Rcpp::wrap(rhierMnlRwMixture_rcpp_loop(lgtdata, Z, deltabar, Ad, mubar, Amu, nu, V, s, R, keep, nprint, drawdelta, olddelta, a, oldprob, oldbetas, ind, SignRes, p_it_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_maxdiff_llmnl_con", (DL_FUNC) &_maxdiff_llmnl_con, 5},
    {"_maxdiff_rhierMnlRwMixture_rcpp_loop", (DL_FUNC) &_maxdiff_rhierMnlRwMixture_rcpp_loop, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_maxdiff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
