# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llmnl_con <- function(betastar, y, X, SignRes = as.numeric( c(0)), p_vec = as.integer( c())) {
    .Call('_maxdiff_llmnl_con', PACKAGE = 'maxdiff', betastar, y, X, SignRes, p_vec)
}

rhierMnlRwMixture_rcpp_loop <- function(lgtdata, Z, deltabar, Ad, mubar, Amu, nu, V, s, R, keep, nprint, drawdelta, olddelta, a, oldprob, oldbetas, ind, SignRes, p_it_list) {
    .Call('_maxdiff_rhierMnlRwMixture_rcpp_loop', PACKAGE = 'maxdiff', lgtdata, Z, deltabar, Ad, mubar, Amu, nu, V, s, R, keep, nprint, drawdelta, olddelta, a, oldprob, oldbetas, ind, SignRes, p_it_list)
}

